"""Evaluate native Terraform with mock providers ONLY. Never plan against an account."""

import json
import os
import re
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]


def run(argv, cwd, env):
    result = subprocess.run(
        argv, cwd=cwd, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False
    )
    if result.returncode:
        raise AssertionError(f"Child failed ({result.returncode}): {' '.join(argv)}\n{result.stdout}")
    return result.stdout


class TerraformPlans:
    def __init__(self, directory):
        self.directory = directory
        self.env = {k: v for k, v in os.environ.items() if not k.startswith(("AWS_", "TF_VAR_", "TF_CLI_ARGS"))}
        self.env.update(
            AWS_EC2_METADATA_DISABLED="true",
            AWS_SHARED_CREDENTIALS_FILE="/dev/null",
            AWS_CONFIG_FILE="/dev/null",
            TF_IN_AUTOMATION="1",
            CHECKPOINT_DISABLE="1",
            TF_CLI_CONFIG_FILE="/dev/null",
        )
        self.roots = {}

    def __call__(self, module, variables):
        if module not in self.roots:
            target = self.directory / module
            shutil.copytree(
                ROOT / "terraform/modules" / module, target, ignore=shutil.ignore_patterns(".terraform", "tests")
            )
            run(["terraform", "init", "-backend=false", "-input=false", "-no-color"], target, self.env)
            self.roots[module] = target
        target = self.roots[module]
        mocks = {
            "aws": {
                "override_during": "plan",
                "mock_data": {
                    "aws_caller_identity": {"defaults": {"account_id": "123456789012"}},
                    "aws_region": {"defaults": {"name": "us-east-1"}},
                },
            }
        }
        # Specify a mock rule per resource type, so computed IDs are available in the plan.
        # Only computed values are mocked; configured values still come from the real module.
        types = set(re.findall(r'resource "([^"]+)"', "\n".join(p.read_text() for p in target.glob("*.tf"))))
        arn = "arn:aws:testing:us-east-1:123456789012:synthetic"
        mocks["aws"]["mock_resource"] = {
            t: {"defaults": {"arn": arn}, "override_during": "plan"} for t in types if t.startswith("aws_")
        }
        for t, defaults in {
            "aws_lb": {"arn": "arn:aws:elasticloadbalancing:us-east-1:123456789012:loadbalancer/app/test/123"},
            "aws_lb_target_group": {"arn": "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/test/123"},
            "aws_iam_role": {"arn": "arn:aws:iam::123456789012:role/test"},
            "aws_secretsmanager_secret": {
                "arn": "arn:aws:secretsmanager:us-east-1:123456789012:secret:test-abcdef",
                "id": "arn:aws:secretsmanager:us-east-1:123456789012:secret:test-abcdef",
            },
            "aws_cloudwatch_log_group": {"arn": "arn:aws:logs:us-east-1:123456789012:log-group:test"},
            "aws_kms_key": {
                "arn": "arn:aws:kms:us-east-1:123456789012:key/00000000-0000-0000-0000-000000000001",
                "key_id": "00000000-0000-0000-0000-000000000001",
            },
        }.items():
            if t in mocks["aws"]["mock_resource"]:
                mocks["aws"]["mock_resource"][t]["defaults"] = defaults
        versions = (target / "versions.tf").read_text()
        for provider in ["random", "tls"]:
            if f"hashicorp/{provider}" in versions:
                mocks[provider] = {
                    "override_during": "plan",
                    "mock_resource": {
                        t: {"defaults": {}, "override_during": "plan"} for t in types if t.startswith(provider + "_")
                    },
                }
        # No apply, no real provider: the test plan's computed values are generated by Terraform.
        test = {"mock_provider": mocks, "run": {"contract": {"command": "plan", "variables": variables}}}
        # Distinct computed identity markers let assertions follow actual attachment/target graphs.
        overrides = []

        def identity(target, name, service="iam", resource="role"):
            region = "" if service == "iam" else "us-east-1"
            overrides.append(
                {
                    "target": target,
                    "override_during": "plan",
                    "values": {
                        "id": name,
                        "arn": f"arn:aws:{service}:{region}:123456789012:{resource}/{name}",
                    },
                }
            )

        if module == "ecs-app":
            for color in ["blue", "green"] if variables.get("deployment_paradigm") == "blue_green" else ["standalone"]:
                identity(f'aws_lb_target_group.portal["{color}"]', color, "elasticloadbalancing", "targetgroup")
        if module == "codebuild":
            for role in (
                ["portal", "tibanna"]
                + ([] if variables["app_kind"] == "ff" else ["pipeline"])
                + (["external"] if variables["app_kind"] == "cgap" else [])
            ):
                identity(f'aws_iam_role.project["{role}"]', role)
        if module == "iam":
            for policy in ["ecs_secret_manager", "ecs_es", "ecs_sqs", "ecs_ecr", "ecs_s3"]:
                identity(f"aws_iam_policy.{policy}", policy, "iam", "policy")
            if variables["ecosystem_resources"]["kms_keys"]:
                identity("aws_iam_policy.ecs_kms[0]", "ecs_kms", "iam", "policy")
        if module == "srce-network":
            for key in [
                "app_db",
                "app_https",
                "app_application",
                "db_db",
                "db_https",
                "db_application",
                "compute_application",
            ]:
                identity(f'aws_security_group.this["{key}"]', key, "ec2", "security-group")
        if overrides:
            test["override_resource"] = overrides
        (target / "contract.tftest.json").write_text(json.dumps(test))
        output = run(["terraform", "test", "-json", "-verbose", "-no-color"], target, self.env)
        (target / "last-test.jsonl").write_text(output)
        events = [json.loads(line) for line in output.splitlines() if line.startswith("{")]
        plans = [event["test_plan"] for event in events if event.get("type") == "test_plan"]
        assert len(plans) == 1, output
        return plans[0]

    def graph(self, module):
        return run(["terraform", "graph", "-type=plan"], self.roots[module], self.env)


def resources(plan, kind):
    return [dict(r, values=r["change"]["after"]) for r in plan.get("resource_changes", []) if r["type"] == kind]
