"""Locks the clarified deployment boundary: only SMaHT/SRCE stacks and named shared prerequisites.

The captain's scope for this change is a **fresh SMaHT blue/green SRCE deployment**. Fourfront and
the existing CGAP deployments are fixed, so every stack they provision must synthesize exactly as
it does on ``origin/master`` -- for every app kind and both deployment paradigms -- unless it is one
of the explicitly named shared prerequisites the new deployment consumes, and even then only
*additively*.

``tests/parity/fixed_stack_baseline.json`` is the fingerprint of that ``origin/master`` synthesis,
generated by ``tests/parity/synthesis_matrix.py`` run inside a ``git archive`` of ``origin/master``
(see that module's docstring). It is deliberately not produced from this branch.

To regenerate after a legitimate change to a fixed stack lands on master, re-run the generator
against the new master -- never against the branch.
"""
import pytest

from tests.parity import synthesis_matrix as matrix


BASELINE = matrix.load_baseline()

# Registered stacks introduced by this change. They have no baseline because they do not exist on
# origin/master, and they are exactly the surface the fresh SMaHT SRCE deployment adds.
NEW_SRCE_STACKS = {
    'alpha:srce-network', 'alpha:srce-network-db', 'alpha:srce-network-compute',
    'alpha:srce-datastore', 'alpha:srce-redis', 'alpha:srce-ecs', 'alpha:srce-ecs-blue-green',
    'alpha:srce-sentieon',
}

CASES = [(variant, stack) for variant in sorted(BASELINE) for stack in sorted(BASELINE[variant])]


@pytest.fixture(scope='module')
def current():
    """ Synthesis of this branch over the same variant matrix as the baseline. """
    return matrix.build_matrix()


def test_every_registered_stack_is_classified(current):
    """ No stack may slip through unclassified: it is either in the origin/master baseline or in
        the declared list of new SRCE stacks. A forgotten stack shows up here, not silently. """
    for variant, stacks in current.items():
        unclassified = set(stacks) - set(BASELINE[variant]) - NEW_SRCE_STACKS
        assert not unclassified, f'{variant}: unclassified registered stacks {sorted(unclassified)}'
    for variant in BASELINE:
        missing = set(BASELINE[variant]) - set(current[variant])
        assert not missing, f'{variant}: baseline stacks no longer registered {sorted(missing)}'


@pytest.mark.parametrize('variant,stack', CASES, ids=[f'{v}-{s}' for v, s in CASES])
def test_fixed_stack_is_unchanged_or_additive(current, variant, stack):
    expected = BASELINE[variant][stack]
    actual = current[variant][stack]

    # A stack that legitimately refuses to synthesize in a variant must refuse identically.
    assert ('error' in expected) == ('error' in actual), (
        f'{variant} {stack}: synthesis outcome changed\n  master: {expected.get("error", "<ok>")}'
        f'\n  branch: {actual.get("error", "<ok>")}')
    if 'error' in expected:
        assert expected['error'] == actual['error'], f'{variant} {stack}: different failure'
        return

    if stack not in matrix.ADDITIVE_STACKS:
        assert actual['digest'] == expected['digest'], (
            f'{variant} {stack} is fixed Fourfront/existing-CGAP infrastructure but its template '
            f'changed. Diff by logical id:\n' + _describe(expected, actual))
        return

    # Named shared prerequisite: additions permitted, mutations and removals are not.
    reason = matrix.ADDITIVE_STACKS[stack]
    for section in matrix.SECTIONS:
        before, after = expected['sections'][section], actual['sections'][section]
        removed = sorted(set(before) - set(after))
        changed = sorted(key for key in set(before) & set(after) if before[key] != after[key])
        assert not removed, f'{variant} {stack} ({reason}): removed {section} {removed}'
        assert not changed, f'{variant} {stack} ({reason}): mutated {section} {changed}'


def _describe(expected, actual):
    lines = []
    for section in matrix.SECTIONS:
        before, after = expected['sections'][section], actual['sections'][section]
        added = sorted(set(after) - set(before))
        removed = sorted(set(before) - set(after))
        changed = sorted(key for key in set(before) & set(after) if before[key] != after[key])
        for label, keys in (('added', added), ('removed', removed), ('changed', changed)):
            if keys:
                lines.append(f'  {section} {label}: {keys}')
    return '\n'.join(lines) or '  (whole-template digest differs with no per-id difference)'
