#!/usr/bin/env bash

verbose_arg=

verbose=FALSE
if [ "$1" = "-v" -o "$1" = "--verbose" ]; then
    verbose=TRUE
    verbose_arg="--verbose"
    shift 1
fi

keyfile=${S3_ENCRYPT_KEY_FILE:-$(dirname $(dirname $0))/custom/aws_creds/s3_encrypt_key.txt}

if [ "${VERBOSE}" = "TRUE" ]; then
    echo "Keyfile: ${keyfile}"
fi

if [ -e "${keyfile}" ]; then
    echo "The file ${keyfile} already exists."
    if [ "${verbose}" = "TRUE" ]; then
        content=`cat ${keyfile}`
        echo "    \"S3_ENCRYPT_KEY\": \"${content}\""
    fi
else
    echo "The file ${keyfile} does not exist. It will be created."
    $(dirname $0)/create_s3_encrypt_key ${verbose_arg}
fi
