#!/usr/bin/env bash

openssl_vendor=`openssl version | cut -d ' ' -f 1`

if [ -z "${openssl_vendor}" ]; then
  echo "OpenSSL is not installed."
  echo "You can install it on MacOS by using brew."
  exit 1
elif [ "${openssl_vendor}" != "OpenSSL" ]; then
  echo "Your openssl version ($(openssl version) from $(which openssl)) is probably incompatible."
  brew_openssl_dir=`brew --prefix openssl`
  if [ -n "${brew_openssl_dir}" ]; then
    brew_openssl_version=`${brew_openssl_dir}/bin/openssl version | cut -d ' ' -f 1-2`
    echo "Brew has already installed ${brew_openssl_version} on this machine."
    echo "To use the brew version, add this to your ~/.bash_profile or ~/.bashrc:"
    echo "  export PATH=${brew_openssl_dir}/bin:\$PATH"
  else
    echo "You can get the right version on MacOS by using brew."
  fi
  exit 1
fi

if [ ! -e "~/.aws_test" ]; then
  echo "The file ~/.aws_test does not exist. You may not have the right credentials selected."
  exit 1
fi

verbose=FALSE
if [ "$1" = "-v" -o "$1" = "--verbose" ]; then
    verbose=TRUE
    shift 1
fi

keyfile=${S3_ENCRYPT_KEY_FILE:-$HOME/.aws_test/s3_encrypt_key.txt}

if [ -e "${keyfile}" ]; then
    echo "The file ${keyfile} already exists."
    if [ "${verbose}" = "TRUE" ]; then
        content=`cat ${keyfile}`
        echo "    \"S3_ENCRYPT_KEY\": \"${content}\""
    fi
    exit 1
fi

echo "Creating ${keyfile}..."

# Make initially blank version of the file.
touch ${keyfile}
# Make the file unreadable by others
chmod 600 ${keyfile}
# Put data in the file
seed=`ps -ax | md5`
openssl enc -aes-128-cbc -k ${seed} -P -pbkdf2 -a \
   | grep '^key=' \
   | sed -E 's|^key=(.*)$|\1|' \
   > ${keyfile}

# Make it so we can't delete the file accidentally
chmod 400 ${keyfile}
content=`cat ${keyfile}`

echo "Created: ${keyfile}"
if [ "${verbose}" = "TRUE" ]; then
  echo "NOTE: Please copy this value into config.json as S3_ENCRYPT_KEY and then safeguard this secret."
  echo "    \"S3_ENCRYPT_KEY\": \"${content}\""
  echo "If you delete the secret your data will be lost without it."
fi
