#!/usr/bin/env bash

# To use this script, fill out the buckets you want to ls/delete in
# delete_pending_buckets.data.txt. Output is streamed into files in
# the out/ directory. BE EXTREMELY CAREFUL. You will need
# to confirm the deletion of every bucket. Note that this will NOT
# remove versions if you enable object versioning. The easiest way to
# deal with versions is from the AWS console

# shellcheck disable=SC2013
for i in $(cat delete_pending_buckets.data.txt)
do
  echo "force deleting ${i}..."
  docker run --rm -ti -v ~/.aws_test:/root/.aws amazon/aws-cli s3 ls s3://${i} --summarize
  echo "Enter any key to confirm"
  read _
  echo "follow progress with:"
  echo "tail -f ../out/delete_log_${i}.log"
  docker run --rm -ti -v ~/.aws_test:/root/.aws amazon/aws-cli s3 rb s3://${i} --force >> ../out/delete_log_${i}.log
done

echo "All done."
