#!/usr/bin/env bash

set -v -x

# To test, uncomment the ls line, comment the rb --force line, and run
# Outputs saved to the out/ gitignored dir

for i in `cat delete-pending-buckets.data.txt`
do
  echo "force deleting ${i}...press key to proceed or ctrl+c to cancel"
  read line
  echo "follow progress with:"
  echo "tail -f ../out/delete_log_${i}.log"
  #docker run --rm -ti -v ~/.aws:/root/.aws amazon/aws-cli s3 rb s3://${i} --force >> ../out/delete_log_${i}.log
  docker run --rm -ti -v ~/.aws:/root/.aws amazon/aws-cli s3 ls s3://${i} --summarize >> ../out/delete_log_${i}.log
done

echo "All done."
