#!/usr/bin/env bash

#docker pull 4dndcic/tibanna-awsf:"$TIBANNA_VERSION"
#docker build -t 4dndcic/tibanna-awsf:"$TIBANNA_VERSION" --build-arg version="$TIBANNA_VERSION" awsf3-docker/
docker tag 4dndcic/tibanna-awsf:"$TIBANNA_VERSION" "$ACCOUNT_NUMBER".dkr.ecr.us-east-1.amazonaws.com/tibanna-awsf:"$TIBANNA_VERSION"
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ACCOUNT_NUMBER}.dkr.ecr.us-east-1.amazonaws.com
docker push "$ACCOUNT_NUMBER".dkr.ecr.us-east-1.amazonaws.com/tibanna-awsf:"$TIBANNA_VERSION"

