class GacSecretKeyName:
    ACCOUNT_NUMBER = "ACCOUNT_NUMBER"
    ENCODED_IDENTITY = "ENCODED_IDENTITY"
    ENCODED_ES_SERVER = "ENCODED_ES_SERVER"
    ENCODED_S3_ENCRYPT_KEY_ID = "ENCODED_S3_ENCRYPT_KEY_ID"
    RDS_HOSTNAME = "RDS_HOSTNAME"
    RDS_PASSWORD = "RDS_PASSWORD"
    S3_AWS_ACCESS_KEY_ID = "S3_AWS_ACCESS_KEY_ID"
    S3_AWS_SECRET_ACCESS_KEY = "S3_AWS_SECRET_ACCESS_KEY"


class RdsSecretKeyName:
    RDS_HOSTNAME = "host"
    RDS_PASSWORD = "password"
